---
- name: "Setup NFS server"
  hosts: storage-servers
  roles:
    - storage
  tags:
    - swarm

- name: "Install basic softwares, tools and dependencies"
  hosts: manager-servers, worker-servers
  roles:
    - base
  tags:
    - swarm

- name: "Join managers to cluster"
  hosts: manager-servers
  roles:
    - managers
  tags:
    - swarm
    - setup
    - label
    - manager

- name: "Join workers to cluster"
  hosts: worker-servers
  roles:
    - workers
  tags:
    - swarm
    - worker

- name: "Deploy monitoring stack"
  hosts: all
  roles:
    - monitoring
  tags:
    - swarm
    - monitoring

- name: "Cleanup"
  hosts: manager-servers, worker-servers
  tasks:
    - name: "Prune containers, networks, volumes"
      community.docker.docker_prune:
        containers: true
        networks: true
        volumes: true
  tags:
    - swarm
    - cleanup
