---
- name: "Set hostname"
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: "Create shared dir"
  ansible.builtin.file:
    path: "/shared/"
    state: directory

- name: "Install NFS server"
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: "Config NFS server"
  ansible.builtin.copy:
    src: "files/nfs-config"
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: "Restart NFS service"
