---
- name: "Setup Dirs tasks for etcd"
  tags:
    - etcd
  block:
    - name: "Copy etcd .env config"
      ansible.builtin.template:
        src: "etcd/.env.j2"
        dest: "/shared/stacks/percona/compose/.env.etcd"
        owner: "root"
        group: "root"
        mode: "0644"
  when: inventory_hostname in groups['manager-servers'][0]
