---
- name: "Setup Dirs tasks for proxysql"
  tags:
    - etcd
  block:
    - name: "Copy proxysql .env config"
      ansible.builtin.template:
        src: "proxysql/.env.j2"
        dest: "/shared/stacks/percona/compose/.env.proxysql"
        owner: "root"
        group: "root"
        mode: "0644"
  when: inventory_hostname in groups['manager-servers'][0]
