---
- name: "Include Base tasks"
  ansible.builtin.include_tasks:
    file: base.yml
  tags:
    - base

- name: "Include NFS tasks"
  ansible.builtin.include_tasks:
    file: nfs.yml
  tags:
    - nfs
    
- name: "Include Docker tasks"
  ansible.builtin.include_tasks:
    file: docker.yml
  tags:
    - docker
