---
- name: "HAProxy tasks"
  tags:
    - haproxy
  block:
    - name: "Create dirs"
      ansible.builtin.file:
        path: "/shared/stacks/{{ item }}"
        owner: "root"
        group: "root"
        mode: "0644"
        state: directory
      with_items:
        - "haproxy/compose"
        - "haproxy/config"

    - name: "Copy config file"
      ansible.builtin.template:
        src: "haproxy/haproxy.cfg.j2"
        dest: "/shared/stacks/haproxy/config/haproxy.cfg"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: "Reload HAProxy"

    - name: "Copy docker-compose file"
      ansible.builtin.template:
        src: "haproxy/docker-compose.yml.j2"
        dest: "/shared/stacks/haproxy/compose/docker-compose.yml"
        owner: "root"
        group: "root"
        mode: "0644"
      notify: "Deploy HAProxy"
