---
vrrp_ip: 192.168.150.100/32
haproxy_image: haproxytech/haproxy-debian:2.0

haproxy:
  networks:
    - network: "monitoring"
      stack: "cluster-monitoring"
    - network: "proxysql"
      stack: "percona"
#    - network: "vault"
#      stack: "vault"
  services:
    http:
      - name: grafana
        port: 3000
        domain: "grafana.office.lab"
    tcp:
      - name: percona-proxysql
        port: 3306
        domain: "proxysql.office.lab"
#    - name: vault
#      port: 8200
#      domain: "vault.office.lab"