---
- name: "Include Setup tasks"
  ansible.builtin.include_tasks:
    file: setup.yml
  tags:
    - swarm
    - setup
    - manager

- name: "Include label tasks"
  ansible.builtin.include_tasks:
    file: label.yml
  tags:
    - swarm
    - label
    - manager
