---
- name: "Include Partitioning tast"
  ansible.builtin.include_tasks:
    file: partitioning.yml
  tags:
    - swarm
    - storage

- name: "Include NFS tast"
  ansible.builtin.include_tasks:
    file: nfs.yml
  tags:
    - swarm
    - storage
