---
- name: "Base tasks"
  tags:
  - base
  block:
    - name: "Set hostname"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        
    - name: "Install packages"
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - vim
          - ca-certificates
          - python3-yaml
        state: present
        