- name: "Daemon reload"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Restart Prometheus Node Exporter"
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter
    state: restarted
