---
- name: "Prometheus tasks"
  tags:
    - prometheus
  block:
    - name: "Install Prometheus Node exporter"
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
        state: present

    - name: "Create monitoring stack dir"
      ansible.builtin.file:
        path: "/etc/systemd/system/prometheus-node-exporter.service.d"
        owner: "root"
        group: "root"
        state: directory

    - name: "Override defaults"
      ansible.builtin.template:
        src: "prometheus-node-exporter_override.j2"
        dest: "/etc/systemd/system/prometheus-node-exporter.service.d/override.conf"
        mode: "0644"
        owner: "root"
        group: "root"
      notify:
        - "Daemon reload"
        - "Restart Prometheus Node Exporter"
        